base: &BASE
  min_messages: WARNING
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 20

development:
  <<: *BASE
  database: spielvolk_development

staging:
  <<: *BASE
  database: spielvolk_development

production:
  <<: *BASE
  database: spielvolk_development

test: &test
  <<: *BASE
  database: spielvolk_test
  timeout: 5000

cucumber:
  <<: *test
